# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 27, 13, 8, 9, 804795, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
