# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0003_auto_20160827_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='item_images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloth_images', to='apparel.Cloth'),
        ),
    ]
