# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0004_auto_20160827_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=300)),
                ('item_brand', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Men', 'Male'), ('Women', 'Female')], max_length=100)),
                ('item_price', models.IntegerField()),
                ('item_color', models.CharField(max_length=100)),
                ('is_in_stock', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('SLIP-ONS', 'SLIP-ONS'), ('HIGH TOPS', 'HIGH TOPS'), ('LOW TOPS', 'LOW TOPS'), ('SANDALS & FLIP FLOPS', 'SANDALS & FLIP FLOPS'), ('SNEAKERS & PLIMSOLLS', 'SNEAKERS & PLIMSOLLS'), ('FORMAL', 'FORMAL'), ('SPORTS', 'SPORTS'), ('BOOTS', 'BOOTS'), ('BROGUES & DERBIES', 'BROGUES & DERBIES')], default='Category', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='size',
            name='sizes',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], max_length=25),
        ),
        migrations.AddField(
            model_name='shoe',
            name='sizes',
            field=models.ManyToManyField(related_name='shoe_size', to='apparel.Size'),
        ),
    ]
