# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0006_auto_20160830_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='item_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='item_price',
            field=models.FloatField(),
        ),
    ]
