# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0015_auto_20160915_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
