# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0018_auto_20160917_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='item_image',
            new_name='itemImage',
        ),
    ]
