# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0020_auto_20160918_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='item_size', to='apparel.Size'),
        ),
    ]
