# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-25 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0024_auto_20161105_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
