# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0002_cloth_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='sizes',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35')], max_length=25),
        ),
    ]
