# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0005_auto_20160829_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='sizes',
            field=models.CharField(max_length=25),
        ),
    ]
