# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0010_auto_20160831_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='category',
            field=models.CharField(default='Category', max_length=200),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(default='Category', max_length=200),
        ),
    ]
