# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0012_auto_20160831_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(default='Item Type', max_length=250),
            preserve_default=False,
        ),
    ]
