# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0021_auto_20160920_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('cash_on_delivery', models.BooleanField(default=False)),
                ('paybal', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_item', to='apparel.Item')),
            ],
        ),
    ]
