# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0022_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paybal',
            new_name='paypal',
        ),
    ]
